// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjVLXwzScissUPl30lMLLm-gPxS69idbY',
    appId: '1:50798018907:web:6fbca6dbb67f532b049a7e',
    messagingSenderId: '50798018907',
    projectId: 'muhandis-6b8c4',
    authDomain: 'muhandis-6b8c4.firebaseapp.com',
    storageBucket: 'muhandis-6b8c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgYBPb956mTh6OfULIn_98U4Pgo0bcvA',
    appId: '1:50798018907:android:62668aab686df0a5049a7e',
    messagingSenderId: '50798018907',
    projectId: 'muhandis-6b8c4',
    storageBucket: 'muhandis-6b8c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAw-73rDXKnJdUBWVXOr_ptoO1-22fGnY',
    appId: '1:50798018907:ios:65bd022a881712be049a7e',
    messagingSenderId: '50798018907',
    projectId: 'muhandis-6b8c4',
    storageBucket: 'muhandis-6b8c4.appspot.com',
    iosBundleId: 'com.example.muhandis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAw-73rDXKnJdUBWVXOr_ptoO1-22fGnY',
    appId: '1:50798018907:ios:dbc26aa586ecb4fe049a7e',
    messagingSenderId: '50798018907',
    projectId: 'muhandis-6b8c4',
    storageBucket: 'muhandis-6b8c4.appspot.com',
    iosBundleId: 'com.example.muhandis.RunnerTests',
  );
}
